# Author: Pfahli
# Version: 0.2
# Project: ultimateXnova

version: '3.8'

services:
  web:
    build: .
    ports:
      - "3838:80"
    volumes:
      - .:/var/www/html/
    depends_on:
      - db
    # This service serves the PHP application via Apache

  db:
    image: mysql:5.7
    ports:
    - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: uxn_root_password
      MYSQL_DATABASE: ultimatexnova
      MYSQL_USER: uxn_user
      MYSQL_PASSWORD: uxn_password
    volumes:
      - dbdata:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 3839:80
    # MySQL database service with persistent storage

volumes:
  dbdata:
    # Persistent volume for MySQL database
